### ISSUE TITLE
Adding more info to the Ludusavi manifest

### ISSUE THREAD

**Issue by mtkennerly** [MikeMaximus/gbm#269]
Hi! I was excited to see that you incorporated support for the Ludusavi manifest 🎉 I was wondering, would it be helpful for GBM if the manifest contained some more info, like the game executable? I could add it from Steam's API (into the manifest's `steam` section), and I think it'd be appropriate for the manifest since you can either use it for process monitoring or as a heuristic for whether a game is installed. There are some cases where it would match up:

* Dark Souls: Remastered
  * GBM monitored process: `DarkSoulsRemastered`
  * Steam config.launch.0.executable: `DarkSoulsRemastered.exe`

...and some where it wouldn't:

* Elden Ring:
  * GBM monitored process: `eldenring`
  * Steam config.launch.0.executable: `Game/start_protected_game.exe`

Would you be interested in this or any other data?

**Comment by MikeMaximus** [comment]
Hey there, thanks for your work developing the manifest!  It's already been really handy for me having access to it in GBM and hopeful for everyone else once I get the release ready.

Yes I think it would be great to have the executable in the manifest.  As you pointed out it's not going to work when a game uses some kind of launcher executable, but more often than not it should provide the correct process to monitor.

Other data that would be handy is the executable's arguments and the OS the executable is for.

**Comment by mtkennerly** [comment]
This is now available: https://github.com/mtkennerly/ludusavi-manifest/commit/a046c18ad47801a9e311aabb932ca4149ecaef32

Here's an example:

```yaml
Some Game:
  launch:
    <base>/Game.exe:
      - when:
          - os: windows
            store: steam
      - arguments: '--win64'
        when:
          - bit: 64
            os: windows
            store: steam
        workingDir: <base>/subdir
```

* Can be launched without arguments on any Windows
* Can be launched with `--win64` argument and specific working directory on 64-bit Windows

**Comment by MikeMaximus** [comment]
Thanks!  I didn't run into any issues.  

It's going to need some tweaking since I didn't have nearly enough coffee today, but GBM now makes it's best guess for monitored process.

**Comment by mtkennerly** [comment]
Awesome :D I noticed a couple of things:

* It looks like it always checks `when(0).os`. There may not be any cases of it right now, but the schema does allow `when` to be empty (although, in practice, the manifest updater should omit it when empty) or to contain more than one item (e.g., if 32-bit and 64-bit Windows use the same launch config).
* This is probably just because I'm not familiar with VB, but in 3911cf963fc017834cf2363b03ce4ce01f53f201, the previous `oWhen As List(Of LudusaviWhen)` seemed like it was correct to me, since `when` is an array of objects.
* It doesn't look like `bit` is currently being checked. You may want to check the user's system (or do conditional compilation based on GBM's 32/64-bit release) to avoid using 64-bit launch configuration on 32-bit systems (and maybe even to prefer 64-bit config on 64-bit systems).

**Comment by MikeMaximus** [comment]
Thanks for the tips 👍 

- Good call, I will add a check empty for an ```when```.
- In VB ```LudusaviWhen()``` is a dynamic array declaration, the array should be a little faster than the ```List```.
- I'm still pondering how to handle the ```bit``` field.  I do want to have it choose the launch config based on the current architecture, I'm just currently unsure of the best method that's going to work for me in Windows and Linux.

**Comment by mtkennerly** [comment]
Nice :+1: One last small thing about this part:

https://github.com/MikeMaximus/gbm/blob/3a8655e977c0f548aeba71363da32c9ba9853f05/GBM/Managers/mgrLudusavi.vb#L234-L235

Is this missing a `For Each oLudusaviWhen In oLudusaviLaunch.when`, or is that handled elsewhere/implicitly? I think the following config would cause Game.exe to be added to oSecondaryRanked on a 64-bit system:

```yaml
Some Game:
  launch:
    <base>/Game.exe:
      - when:
          - os: windows
            store: steam
          - bit: 64
            os: windows
            store: steam
```

...since this check looks like it's only for the first item in the `when` list:

https://github.com/MikeMaximus/gbm/blob/3a8655e977c0f548aeba71363da32c9ba9853f05/GBM/Managers/mgrLudusavi.vb#L253
